# Generated by Django 3.1.7 on 2022-06-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='descriptions',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Detail_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('descriptions', models.CharField(max_length=500)),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='detail_lugar_image/')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='Galeria_image_Place/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='Galeria_image_Place/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='Galeria_image_Place/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='Galeria_image_Place/')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='Galeria_image_Place/')),
                ('image_six', models.ImageField(blank=True, null=True, upload_to='Galeria_image_Place/')),
                ('image_recommen', models.ImageField(blank=True, null=True, upload_to='Image_recommen/')),
                ('recommendation', models.CharField(max_length=500)),
                ('ubicacion', models.CharField(max_length=500)),
                ('place', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Places.place')),
            ],
        ),
    ]
