# Generated by Django 3.1.7 on 2022-06-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_auto_20220621_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_place',
            name='de_place_image',
            field=models.ImageField(blank=True, null=True, upload_to='detail_place_tour_image/'),
        ),
    ]
