# Generated by Django 3.1.7 on 2022-06-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0004_remove_detail_place_de_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_place',
            name='detail_image',
        ),
    ]
