# Generated by Django 4.0.3 on 2022-06-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0004_remove_detail_place_de_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_place',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detail_place',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
