# Generated by Django 4.0.3 on 2022-06-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0005_alter_category_place_id_alter_detail_place_id_and_more'),
        ('Places', '0005_remove_detail_place_detail_image'),
    ]

    operations = [
    ]
