# Generated by Django 4.0.3 on 2022-05-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categoria-servicios')),
                ('recomendacion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('categoriaservicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.categoriaservicio')),
                ('lugares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.lugares')),
                ('planservicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.planservicio')),
            ],
            options={
                'verbose_name': 'detallecategoria',
                'verbose_name_plural': 'detallescategoria',
            },
        ),
    ]
