# Generated by Django 3.1.7 on 2022-06-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_servicio',
            name='servicio',
        ),
        migrations.AddField(
            model_name='detail_servicio',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='detail_servicio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.detail_servicio'),
        ),
    ]
