# Generated by Django 3.1.7 on 2022-06-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20220609_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='detail_servicio',
        ),
        migrations.AddField(
            model_name='detail_servicio',
            name='servicio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio'),
        ),
    ]
