# Generated by Django 3.1.7 on 2022-06-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_detail_place_tour_de_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_place_tour',
            name='de_place_image',
        ),
    ]
