# Generated by Django 3.1.7 on 2022-06-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20220610_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
