# Generated by Django 4.0.3 on 2022-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_detallecategoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecategoria',
            name='categoriaservicio',
        ),
        migrations.AddField(
            model_name='detallecategoria',
            name='categoriaservicio',
            field=models.ManyToManyField(to='Servicios.categoriaservicio'),
        ),
    ]
