# Generated by Django 3.1.7 on 2022-06-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_guia_tour'),
        ('servicios', '0004_detail_place_tour_de_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_place_tour',
            name='guia_tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpage.guia_tour'),
        ),
        migrations.DeleteModel(
            name='Guia_tour',
        ),
    ]
