# Generated by Django 3.1.7 on 2022-06-21 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20220621_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('decriptions', models.CharField(max_length=40)),
                ('picture', models.ImageField(upload_to='guia_image/')),
            ],
        ),
        migrations.AlterField(
            model_name='detail_place_tour',
            name='guia_tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.guia_tour'),
        ),
    ]
