# Generated by Django 4.0.3 on 2022-05-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_remove_detallecategoria_categoriaservicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecategoria',
            options={'verbose_name': 'detalle', 'verbose_name_plural': 'detalles'},
        ),
    ]
