# Generated by Django 4.0.3 on 2022-05-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0006_alter_detallecategoria_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecategoria',
            old_name='categoriaservicio',
            new_name='categorias',
        ),
        migrations.RenameField(
            model_name='detallecategoria',
            old_name='planservicio',
            new_name='planes',
        ),
        migrations.AlterField(
            model_name='detallecategoria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detalle-categoria'),
        ),
    ]
