# Generated by Django 3.1.7 on 2022-06-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20220621_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='place_tour',
            name='category',
        ),
        migrations.AlterField(
            model_name='detail_place_tour',
            name='detail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='detail_place_tour',
            name='recommendation',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='guia_tour',
            name='decriptions',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='place_tour',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='detail_place_tour',
            name='movilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.movilidad'),
        ),
    ]
