# Generated by Django 4.0.3 on 2022-05-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0007_rename_categoriaservicio_detallecategoria_categorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecategoria',
            name='planes',
        ),
    ]
