# Generated by Django 3.1.7 on 2022-06-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20220622_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='movilidad',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True),
        ),
    ]
