# Generated by Django 3.1.7 on 2022-06-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_movilidad_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movilidad',
            name='status',
        ),
        migrations.AddField(
            model_name='detail_place_tour',
            name='status_movilidad',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True),
        ),
    ]
