# Generated by Django 3.1.7 on 2022-06-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20220622_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_place_tour',
            name='movilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.movilidad'),
        ),
    ]
