# Generated by Django 3.1.7 on 2022-06-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_auto_20220622_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_place_tour',
            name='status_movilidad',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
    ]
