# Generated by Django 3.1.7 on 2022-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_auto_20220622_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='movilidad',
            name='descriptions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
