# Generated by Django 4.0.3 on 2022-06-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_detail_place_tour_id_alter_place_tour_id'),
        ('servicios', '0012_movilidad_descriptions'),
    ]

    operations = [
    ]
