# Generated by Django 3.1.7 on 2022-06-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_movilidad_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_tour',
            name='price_menor',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
