# Generated by Django 3.1.7 on 2022-06-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_place_tour_price_menor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_place_tour',
            name='detail',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='detail_place_tour',
            name='recommendation',
            field=models.CharField(max_length=150),
        ),
    ]
