# Generated by Django 4.0.3 on 2022-05-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_service', models.CharField(max_length=100)),
                ('descripcion_service', models.CharField(max_length=200)),
                ('costo_service', models.CharField(max_length=5)),
                ('image_service', models.ImageField(upload_to='servicios')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
