# Generated by Django 3.1.7 on 2022-06-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('decriptions', models.CharField(max_length=40)),
                ('picture', models.ImageField(upload_to='guia_image/')),
            ],
        ),
    ]
