# Generated by Django 3.1.7 on 2022-06-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20220621_1705'),
        ('webpage', '0002_guia_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guia_tour',
        ),
    ]
