# Generated by Django 4.0.3 on 2022-06-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_feedback_id_alter_guia_tour_id'),
        ('webpage', '0003_delete_guia_tour'),
    ]

    operations = [
    ]
